name: ESLint Check
on:
  pull_request:
    branches: ["graphql"]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - ".github/workflows/eslint-check.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Set this to your Node.js version
      - name: Install Dependencies
        run: npm install
      - name: Run ESLint
        run: |
          result=$(npx eslint 'src/**/*.{ts,tsx}' --quiet; echo $?)
          if [ $result -ne 0 ]; then
            echo "ESLint check failed"
            exit 1
          fi
      - name: Check for TypeScript errors
        run: npx tsc --noEmit
